name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: bash ./build_linux.sh

  build_macos:
  
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: bash build_linux.sh
